### ISSUE TITLE
需要增删改的功能建议

### ISSUE THREAD

**Issue by GhostFlys** [Clayun/coi-realm#24]
1.积分面板增加团队积分记录 √
2.小队名字颜色 √
3.远程没有伤害 √
4.关闭死亡掉落 √
5.死亡复活增加CD √
6.防御塔攻击最近玩家改成最近敌人 √
7.防御塔根据基地等级解锁最大数量 √
8.NPC不掉落装备 √
9.铁匠铺开启购买菜单 √
10.建筑攻击核心才能受到伤害 [拒绝设置]
11.NPC指挥功能的增加 [尚未完成]
12.NPC容易跟丢玩家 [尚未完成]
13.防御塔应能攻击NPC √

**Comment by Clayun** [comment]
标记为尚未完成的重新提交了新的ISSUES
