### ISSUE TITLE
铁匠铺数量未限制[Two blacksmith shops]

### ISSUE THREAD

**Issue by SeaOrangejuice** [Clayun/coi-realm#36]
我在游戏中造出了超出数量的铁匠铺。
I built an excessive number of blacksmiths in the game.
![bug](https://github.com/Clayun/coi-realm/assets/116551329/f88cda4f-a0b3-4eb3-9ce0-081556622b2e)

**Comment by Clayun** [comment]
好的,列入BUG修改list
