### ISSUE TITLE
玩家人数分配不均[Uneven distribution of players]

### ISSUE THREAD

**Issue by SeaOrangejuice** [Clayun/coi-realm#37]
玩家人数没法平均分配，大部分玩家在开局会跟其它玩家选择同一个队伍，导致对面队伍缺少玩家。
The number of players cannot be evenly distributed. Most players will choose the same team as other players at the beginning of the game, resulting in a lack of players in the opposing team.
![bugnum](https://github.com/Clayun/coi-realm/assets/116551329/53eb8640-af5d-4c09-a226-9f8859d69cbd)

**Comment by Clayun** [comment]
已临时修改为不予选队,全自动分配
